// <auto-generated />
using FolkaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolkaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819123740_AddCartItemsTable")]
    partial class AddCartItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("FolkaAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FolkaAPI.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Category = "Çanta",
                            Description = "Yüksek kaliteli iplikle elde örülmüş, güzel ve dayanıklı bir bez çanta. Günlük kullanım için mükemmeldir.",
                            Image = "http://10.0.2.2:5227/images/totteBag.webp",
                            Name = "Hand-Knitted Tote Bag",
                            Price = "250 TL",
                            Stock = 8
                        },
                        new
                        {
                            Id = "2",
                            Category = "Takı",
                            Description = "Bu eşsiz, el yapımı püsküllü kolye ile tarzınıza bohem-şık bir dokunuş katın.",
                            Image = "http://10.0.2.2:5227/images/tassel.jpg",
                            Name = "Bohemian Tassel Necklace",
                            Price = "120 TL",
                            Stock = 15
                        },
                        new
                        {
                            Id = "3",
                            Category = "Çanta",
                            Description = "Zarif, el yapımı omuz çantası. Her kıyafetle uyum sağlar.",
                            Image = "https://picsum.photos/seed/bag2/400/400",
                            Name = "El Örgüsü Omuz Çantası",
                            Price = "350 TL",
                            Stock = 5
                        },
                        new
                        {
                            Id = "4",
                            Category = "Fular",
                            Description = "Güzel bir çiçek baskısına sahip, hafif ve yumuşak bir ipek fular. Çok yönlü ve şık.",
                            Image = "http://10.0.2.2:5227/images/fular.webp",
                            Name = "Silk Floral Scarf (Fular)",
                            Price = "150 TL",
                            Stock = 20
                        },
                        new
                        {
                            Id = "5",
                            Category = "Takı",
                            Description = "925 ayar gümüş, el işçiliği hayat ağacı kolye.",
                            Image = "https://picsum.photos/seed/necklace2/400/400",
                            Name = "Gümüş Hayat Ağacı Kolye",
                            Price = "450 TL",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("FolkaAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Address = "Folka Sanat Sokağı, No:12",
                            Email = "dilara@email.com",
                            Name = "Dilara",
                            PasswordHash = "$2a$11$6czEq3jqxd33yQeZKWSGteUzDigkSa4zEqQiyndKNfQkhK7jEp6yK,",
                            PhoneNumber = "+90 555 123 4567"
                        },
                        new
                        {
                            Id = "2",
                            Email = "test@user.com",
                            Name = "Test User",
                            PasswordHash = "$2a$11$Up..XmfOQrriidmoh/lHNuIp7fxpuKDlU8zboh1ecD9.SudkPhfMC"
                        });
                });

            modelBuilder.Entity("FolkaAPI.Models.CartItem", b =>
                {
                    b.HasOne("FolkaAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
